# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 275dc531c07442edef980bfdfc7f76838e2c83fe181cf80ef67e82d36e0aade6dcc4b329f5c0e0671023cb83fc35dd42b32e75b13bee175c88b914564ca9555f

test:
  secret_key_base: 880469653788712183fa4404d2666c2debb067c0899a558e96d2d3443ddb49b077b3222725edbb9e8a665532fb04fcbac08e47767f9648eff3ddaf14530d37b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
