class Limits

  MAX_CANDIDATES_FREE = 5
  MAX_CANDIDATES_BRONZE = 25
  MAX_CANDIDATES_GOLD = 100
  MAX_CANDIDATES_PLATINUM = 500

  MAX_TESTS_FREE = 5
  MAX_TESTS_BRONZE = 10
  MAX_TESTS_GOLD = 50
  MAX_TESTS_PLATINUM = 1000

  MAX_QUESTIONS_FREE = 20
  MAX_QUESTIONS_BRONZE = 50
  MAX_QUESTIONS_GOLD = 200
  MAX_QUESTIONS_PLATINUM = 1000

  MAX_JOB_LISTINGS_FREE = 5
  MAX_JOB_LISTINGS_BRONZE = 25
  MAX_JOB_LISTINGS_GOLD = 100
  MAX_JOB_LISTINGS_PLATINUM = 500
  
end
